### ISSUE TITLE
Q 'Escape : PSQL execution with line break SQL error

### ISSUE THREAD

**Issue by lgming1314** [IvorySQL/IvorySQL#121]
## Bug Report
```
postgres=# select q'[aaa
postgresq# ]';
ERROR:  flex scanner jammed
postgres=#
```
### IvorySQL Version
 PostgreSQL 15devel (IvorySQL 1.0) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
### OS Version (uname -a)
Linux jq02 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
### Expected behavior/code
```
aaa
```

**Comment by gaoxueyu** [comment]
Thanks for your reporting.Issue has been fixed at IvorySQL 3.1.
