### ISSUE TITLE
Something wrong with RPM install

### ISSUE THREAD

**Issue by blatwo** [IvorySQL/IvorySQL#127]
### IvorySQL Version
IvorySQL 1.2
### OS Version (uname -a)
Linux Node02 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
### Configuration options  ( config.status --config )
default install
### Current Behavior
The IvorySQL server couldn't be start when restart Centos7.9, And issued error message as follow:
FATAL:  could not create lock file "/var/run/ivorysql/ivorysql-1/.s.PGSQL.5333.lock": No such file or directory

I think the directory ivorysql-1 is removed from '/run/ivorysql/' when restart Centos7.9 by setting tmpfiles.
When I check the file '/usr/lib/tmpfiles.d/ivorysql-1.conf ' , as follow:
d /run/ivorysql 0755 ivorysql ivorysql -
That's it! I took it replace by follow,
d /run/ivorysql/ivorysql-1 0755 ivorysql ivorysql -
and issued command,
 systemd-tmpfiles --create --remove 
or reboot Centos7.9, it works. I could start the IvorySQL.

### Expected behavior/code
Alter file /usr/lib/tmpfiles.d/ivorysql-1.conf as follow:
d /run/ivorysql/ivorysql-1 0755 ivorysql ivorysql -

**Comment by gaoxueyu** [comment]
Thanks very much for your reporting. Issue has been fixed at IvorySQL 3.1.
