### ISSUE TITLE
It is recommended to improve the problem that identity is created in ivorysql with only the mallint, integer, bigint types.

### ISSUE THREAD

**Issue by ClaudiaY0** [IvorySQL/IvorySQL#128]
It is recommended to improve the problem that identity is created in ivorysql with only the mallint, integer, bigint types.

create table tb_test (
    id number GENERATED ALWAYS AS IDENTITY,
    name varchar(100)
);
> ERROR: identity column type must be smallint, integer, or bigint

**Comment by gaoxueyu** [comment]
Thanks for your reporting. This issue has been fixed at IvorySQL3.
