### ISSUE TITLE
Oracle xml function compatible

### ISSUE THREAD

**Issue by sun-hchao** [IvorySQL/IvorySQL#132]
1. EXTRACT（XMLType_instance，Xpath_string）
This function is used to return the corresponding content under the PATH of the XML node.
Example:
SELECT extract(value(a),'/root/main') data FROM xmltable a ;

2. EXTRACTVALUE（XMLType_instance,Xpath_string)
This function is used to return data for a specific XML node path.
Example:
SELECT extractvalue(value(a),'/root/main/姓名') data FROM xmltable a ;

3. EXISTSNODE（XMLType_instance，Xpath_string）
This function is used to determine whether the path to a particular XML node exists, returning 0 indicates that the node does not exist, and returning 1 indicates that the node exists.
Example:
SELECT existsnode(value(a),'/root/main/住院号') data FROM xmltable a;

4. SYS_DBURIGEN({column|attribute})
This function is used to generate URLs of type DBUrlType based on columns or attributes.
Example:
SELECT sys_dburigen(a.DISPLAYNAME) aa FROM v_dept a WHERE a.DISPLAYNAME='矽肺病医院'

5. SYS_XMLAGG（expr[，fmt]）
This function is used to summarize all XML documents and generate one XML document.
Example:
SELECT SYS_XMLAGG(SYS_XMLGEN(a.order_content)) xml_content
from doc_clinic_order a, clinics_item b, med_frequencydict c
where a.patient_id = 'bd4b425e-a409-4b28-890d-d1d668fcf725'
and a.parentid = '0'
and a.route = b.item_id(+)
and a.frequency = c.frequency_id(+)

6. SYS_XMLGEN(expr[,fmt])
This function is used to generate XMLType instances from the rows and columns of database tables.

7. XMLAGG（XMLType_instance[ORDER BY sort_list])
This function is used to summarize multiple XML blocks and generate XML documents.
Example:
select xmlagg(xmlelement("row",xmlforest(a.frequency_id as "频次ID", a.frequency_name as "频次名称")))[] from med_frequencydict a

8. XMLFOREST（value_expr1[,value_expr2],...)
This function is used to return XML blocks.

9. XMLELEMENT(identifier[,xml_attribute_clause][,value_expr])
This function is used to return an instance of XMLType. where the parameter identifier is used to specify the element name, the parameter xml_attribute_clause is used to specify the element attribute clause, and the parameter value_expr is used to specify the element value.
Example:
SELECT xmlelement("row",xmlcolattval(a.frequency_code AS "编码",a.frequency_name as "名称")) xml
from med_frequencydict a
where a.frequency_code = 'BID'

10. XMLCOLATTVAL（value_expr[,value_expr2],...)
This function is used to generate XML blocks, and the arguments value_expr are used to specify column names or aliases as property names.
Example:
SELECT xmlelement("row",xmlcolattval(a.frequency_code AS "编码", a.frequency_name as "名称")) xml
from med_frequencydict a 
where a.frequency_code = 'BID'

11. XMLCONCAT（XMLType_instance1[,XMLType_instance2],...)
This function is used to concatenate multiple XMLType instances and generate new XMLType instances.
Example:
select xmlconcat(xmltype('1'), xmltype('2'), xmltype('3'))
from dual

12. XMLSEQUENCE（xmltype_instance)
This function is used to return VARIAY elements below the top-level node in an XMLType instance.
Example:
select extractvalue(column_value, '/row/医嘱内容') 医嘱内容
    from table(xmlsequence(extract((select value(a)
    from xmltable a
    where rownum = 1),
'/root/detail/row')))

13. UPDATEXML（XMLType_instance,Xpath_string,value_expr)
This function is used to update the contents of the corresponding node path for a particular XMLType instance.
Example:
select updatexml(xmltype('1名字12名字2'), '/root/row[no=2]/name', '新名字') from dual

14. XMLTRANSFORM（xmltype_instance,xsl_ss)
This function is used to convert XMLType instances in XSL style and generate new XMLType instances.

15. DELETEXML（XMLType_instance,Xpath_string)
This function is used to delete the contents of the corresponding node path for a particular XMLType instance.

16.XML conversion table
SELECT * FROM XMLTABLE('$SQ/root/detail/row' PASSING
    (select value(a) from xmltable a) AS SQ
    COLUMNS 医嘱ID VARCHAR2(50) PATH '/row/医嘱ID',
    医嘱内容 VARCHAR2(200) PATH '/row/医嘱内容',
    频次 VARCHAR2(200) PATH '/row/频次',
    用法 VARCHAR2(200) PATH '/row/用法')
order by 医嘱ID

**Comment by gaoxueyu** [comment]
same with #issue587 and fix by PR #640
