### ISSUE TITLE
Intersection set (INTERSECT) operation fails when there is a varchar2 type in the search result

### ISSUE THREAD

**Issue by liuxintang** [IvorySQL/IvorySQL#146]
## Bug Report
Intersection set (INTERSECT) operation fails when there is a varchar2 type in the search result
### IvorySQL Version
1.3
### OS Version (uname -a)
Linux localhost.localdomain 3.10.0-862.el7.x86_64 https://github.com/IvorySQL/IvorySQL/pull/1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### Configuration options  ( config.status --config )
set compatible_mode =oracle;
### Current Behavior
Test Data:
set compatible_mode =oracle;
create table tb_minus (id int,sname varchar2(10),grade number(3,1));
insert into tb_minus values(1,'A',80.5);
insert into tb_minus values(2,'B',90.1);
insert into tb_minus values(1,'C',80.5);

Test SQL:
select sname from tb_minus intersect select sname from tb_minus where id=2;

Test result:
IvorySQL V1.3：
![image](https://user-images.githubusercontent.com/99459384/174970290-3510e314-13e0-4bef-8e3e-44c0694118e6.png)
Oracle：
![image](https://user-images.githubusercontent.com/99459384/174970330-b54a5886-9acc-41c0-995d-9dbedd9467bf.png)
### Expected behavior/code
Please confirm and fix it.

**Comment by gaoxueyu** [comment]
Issue has been fixe at IvoySQL 3.1. Thanks so much.
