### ISSUE TITLE
create package body fail when use record in overload procedure.

### ISSUE THREAD

**Issue by chirpyli** [IvorySQL/IvorySQL#152]
## Bug Report
create package body fail when use record in overload procedure.
### IvorySQL Version
1.3
### OS Version (uname -a)
Linux pc 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Configuration options  ( config.status --config )
default
### Current Behavior
Test sql:
```sql
create table people(a int, b int);
insert into people values(1,1);
insert into people values(2,2);
create or replace package pkg
as
	procedure show;
	procedure show(a int);
end;
/
-- fail to create package body
create or replace package body pkg
as
	v record;
	procedure show
	is
	begin
		for v in (select * from people) loop
			raise notice 'show1: %', v.a;
		end loop;
	end;
	
	procedure show(a int)
	is
	begin
		for v in (select * from people) loop
			raise notice 'show2: %', v.a;
		end loop;
	end;
end;
/
```
### Expected behavior/code
create package body success.
### Step to reproduce
see Current Behavior test sql

**Comment by rasifr** [comment]
record is a pseudo type and it's not known how many fields it can hold until the runtime. so it's not possible to declare this type of variable at a package level.  However, it should properly generate an error stating that.
