### ISSUE TITLE
Failed to create procedure with $xxxxxx$ in psql

### ISSUE THREAD

**Issue by liuxintang** [IvorySQL/IvorySQL#168]
## Bug Report
If the logical identifier of procedure is "$xxxxxx$", creation fails.
If it is $$, it is created.
But in PostgreSQL 14.5, both of the above cases can be created successfully.
### IvorySQL Version
All versions(1.1~1.5)
### OS Version (uname -a)
Linux localhost.localdomain 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### Configuration options  ( config.status --config )
compatible_mode = postgres
### Current Behavior
Test SQL:
The logical identifier of procedure is "$body$".
```
create or replace procedure proc_test_outpara(vid in integer, ov1 out varchar)
language plpgsql
as
$body$
declare
begin
    if vid = 1 then
        ov1 = 'OK';
    else
        ov1 = 'NG';
    end if;
end;
$body$;
```
Test result:
IvorySQL 1.5: create fail
![image](https://user-images.githubusercontent.com/99459384/191431195-ad3c569d-1a3d-4dc0-8ba9-551036740d74.png)

PostgreSQL 14.5: create success
![image](https://user-images.githubusercontent.com/99459384/191430937-1463d639-e094-4ec2-bbe9-b2cdedc06f40.png)
### Expected behavior
Consistent with PG14.5, the procedure with "$xxxxxx$" is also created successfully.

**Comment by gaoxueyu** [comment]
Bug has been fixed at IvorySQL 3.1.
