### ISSUE TITLE
missing support function 1(16895,25) for attribute 1 of index "test_name_idx"

### ISSUE THREAD

**Issue by Huajianjin** [IvorySQL/IvorySQL#171]
## Bug Report

missing support function 1(16895,25) for attribute 1 of index "test_name_idx"

### IvorySQL Version

All versions(1.1~1.5)

### OS Version (uname -a)

Linux localhost.localdomain 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Configuration options  ( config.status --config )

./configure --prefix=/home/IVORYSQL --enable-debug --enable-cassert CFLAGS='-O0 -g' --enable-tap-tests

### Current Behavior

postgres=# select * from test where name = 'test1';
2022-12-05 13:54:05.240 CST [15604] ERROR:  missing support function 1(16895,25) for attribute 1 of index "test_name_idx"
2022-12-05 13:54:05.240 CST [15604] STATEMENT:  select * from test where name = 'test1';
ERROR:  missing support function 1(16895,25) for attribute 1 of index "test_name_idx"

### Expected behavior/code

select * from test where name = 'test1';
 id |  name   
----+-------
 1 | test1

### Step to reproduce

set compatible_mode to oracle;
create table test(id int, name varchar2(100));
insert into test select a,'test'||a from generate_series(1, 10000) a;
create index on test(name);
select * from test where name = 'test1';

**Comment by gaoxueyu** [comment]
issue have been fixed. Please find the testing result as below:
postgres=# create table test(id int, name varchar2(100));
CREATE TABLE
postgres=# insert into test select a,'test'||a from generate_series(1, 10000) a;
INSERT 0 10000
postgres=# create index on test(name);
CREATE INDEX
postgres=# select * from test where name = 'test1';
 id | name  
----+-------
  1 | test1
(1 row)
