### ISSUE TITLE
Initdb -c Oracle failed to load orafce automatically

### ISSUE THREAD

**Issue by grantzhou** [IvorySQL/IvorySQL#183]
## Bug Report
Initdb -c Oracle failed to load orafce automatically.
This is a feature supported since V1.1,  it was missed in the latest version.
ref:
https://www.ivorysql.org/ivorysql-v1-1-release-page
Automatically load Orafce at initdb 
Orafce extension gets installed automatically with IvorySQL server, so All Oracle compatible objects and types works out of box.

### IvorySQL Version
2.1

### OS Version (uname -a)
CentOS 7

### Step to reproduce
1、Init database

**user can use -c to use postgres or oracle**

**Using "-c oracle" to init database:**

```
[wangzhibin@localhost bin]$ ./initdb -D ../data -c oracle -U postgres
The files belonging to this database system will be owned by user "wangzhibin".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory ../data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Asia/Shanghai
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... loading ivy contrib modules ...
ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
```

**Success. You can now start the database server using:**
```
pg_ctl -D ../data -l logfile start
```

**Startup database**

```
[wangzhibin@localhost bin]$ ./pg_ctl -D ../data -l logfile start
```

Failed command:

```
[wangzhibin@localhost bin]$ ./psql -U postgres -p 5333
psql (15.1)
Type "help" for help.
postgres=# select sysdate from dual;
ERROR:  relation "dual" does not exist
```

**Orafce extension was not loaded automatically**

```
postgres=# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description
---------+---------+------------+------------------------------
 plisql  | 1.0     | pg_catalog | PL/iSQL procedural language
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)
```

**After orafce is created, the following commands will succeed.**

```
postgres=# create extension orafce;
CREATE EXTENSION
postgres=#
postgres=# select sysdate from dual;
  statement_sysdate
---------------------

 2023-01-05 10:14:32
(1 row)
```

Summary:
The orafce shall be loaded automatically depending on the running mode (oracle), so that the user can use the oracle compatibility feature directly.

**Comment by caryhuang** [comment]
In version 2.1, `orafce` extension is no longer loaded automatically during initdb like in release 1.X

An enhancement is made here by Usama that requires users to list all the extension names in a new file called "ivy_module.config" that initdb will read and automatically load. In other words, initdb will only load an extension if it is listed in "ivy_module.config". 

By default, `orafce` is listed in the "ivy_module.config" file, but commented out.

Seems like not loading orafce automatically is intended, as user can still run `initdb` without oracle compatibility option (--compatible-mode=oracle). If this is the case in previous release, orafce extension will still be accidentally loaded and not being used as it does not check current compatibility mode before loading an extension.

possible solution:
update setup documentation and describe the newly added `ivy_module.config` to list extensions that shall be automatically loaded at initdb

**Comment by uhayat** [comment]
Ideally `orafce` should be installed and extension should be present after initdb and user should not be doing `CREATE Extension`. If user want non-oracle compatible cluster they control it with `compatible-mode` configuration variable.
Adding it at initdb requires regression test update thats why It was disabled right after `ivy_module.config` feature was implemented.

If It's okay, I can create pull request with `orafce` enabled and with regression tests updates.

**Comment by killerwzb** [comment]
> Ideally `orafce` should be installed and extension should be present after initdb and user should not be doing `CREATE Extension`. If user want non-oracle compatible cluster they control it with `compatible-mode` configuration variable. Adding it at initdb requires regression test update thats why It was disabled right after `ivy_module.config` feature was implemented.
> 
> If It's okay, I can create pull request with `orafce` enabled and with regression tests updates.

It is good way to deal with it .

**Comment by caryhuang** [comment]
> Ideally `orafce` should be installed and extension should be present after initdb and user should not be doing `CREATE Extension`. If user want non-oracle compatible cluster they control it with `compatible-mode` configuration variable. Adding it at initdb requires regression test update thats why It was disabled right after `ivy_module.config` feature was implemented.
> 
> If It's okay, I can create pull request with `orafce` enabled and with regression tests updates.

You are right, if we were to enable orafce by default in ivy_module.config, regression test will need some updates. It would be great if you could help enable orafce and update the regression. Much appreciated!

**Comment by idrawone** [comment]
it would be great to update the document so that user knows how to enable it properly.

**Comment by gaoxueyu** [comment]
Init database with specified parameter, like "initdb -D ./data-test -m oracle -U postgres".
Document will be updated accordingly.
