### ISSUE TITLE
Sample Package in Doc not working

### ISSUE THREAD

**Issue by luss** [IvorySQL/IvorySQL#23]
Neither the Package Spec nor the Package Body compiles out of the box.    At least in my build from source, the data types of NUMBER and VARCHAR2 are not defined.   Even if you switch to PG data types of VARCHAR & NUMERIC it is still not close to working.   There are also typos and inconsistencies in both the Spec and Body that also cause it not to work.

Also, the code in the samples should use spaces for the indenting.  It seems to use a horrible combination of spaces and tabs that makes a mess when copy/paste into an editor no matter what your tab settings are.

I know it's early days, but, this is important.  It's a users first impression & first experience.

**Comment by rasifr** [comment]
yeah the example in the documentation is not accurate and needs to be fixed. we will update the documentation. Most oracle type are not yet fully supported and the packages still rely on the native pg types. It's a work in progress.

**Comment by codeforall** [comment]
Documentation update for package updated on the website
https://github.com/IvorySQL/Ivory-www/commit/9cbdfe380f9afea00d7bcf291cb4f82008394b29
