### ISSUE TITLE
SELECT sysdate FROM dual  NOT WORKING out of box

### ISSUE THREAD

**Issue by luss** [IvorySQL/IvorySQL#24]
It only worked after I manually ran "CREATE EXTENSION orafce" in the database I was using.

I love that the pgisql extension is installed by default.  I think you should also install orafce and define datatypes such as VARCHAR2 and NUMBER be default.

**Comment by BingAo-Office** [comment]
Hi Denis, 
Thanks a lot for your using. 
Of course, we're going to do that, and we're going to make it easy to use with your help！

Best Regards, 
 Aobing
