### ISSUE TITLE
I would like IvorySQL to have oracle hierarchical queries support 

### ISSUE THREAD

**Issue by rasifr** [IvorySQL/IvorySQL#28]
## Hierarchical Query

Hierarchical queries are very useful to operate on hierarchical data. The PostgreSQL does not support it and It would be a good feature to add into the IvorySQL compatible list. 

The usual clauses for a hierarchical query support are:

```
{ 
CONNECT BY [ NOCYCLE ] condition [AND condition]... [ START WITH condition ] 
| START WITH condition CONNECT BY [ NOCYCLE ] condition [AND condition]...
}
```

**CONNECT BY**
The query syntax starts with CONNECT BY keywords which define the hierarchical interdependency between parent and child rows. The results must be further qualified by specifying the PRIOR keyword in the condition part for CONNECT BY clause.

The PRIOR keyword is a unary operator which links the previous row with the current one. The keyword can be used on the left or the right hand side of the equality condition. In case a loop is detected in the results, an error is returned to the user and the query aborted.

**START WITH**
This clause specified from which row to start the hierarchy.

**NOCYCLE** 
This clause instructs to return data even if a cycle exists.

**Comment by luss** [comment]
+1.  In my opinion this is of the same priority as the (+) syntax for outer
joins (in case on or the other is more difficult to do).

--Luyss

**Comment by luss** [comment]
great stuff.  this is important progress.
