### ISSUE TITLE
Some problems with char varchar varchar2 and nvarchar2

### ISSUE THREAD

**Issue by AndyQinshy** [IvorySQL/IvorySQL#33]
## Bug Report
1. When I set nls_length_semantics to byte, I get an error when I explicitly convert the string to char, varchar, varchar2.
2. nvarchar2 does not distinguish between byte and char.
### IvorySQL Version
1.0
### OS Version (uname -a)
Linux mypg01 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### Configuration options  ( config.status --config )
set nls_length_semantics to byte ;
### Current Behavior
select '我是一个中国人'::char(5);
2022-01-04 11:00:18.204 CST [3010] ERROR:  value too long for type character(5 byte)
2022-01-04 11:00:18.204 CST [3010] STATEMENT:  select '我是一个中国人'::char(5);
ERROR:  value too long for type character(5 byte)

create  table test_12 (id int, a oracle.nvarchar2(5));
CREATE TABLE
insert into test_12 values (1, 'abcde');
INSERT 0 1
insert into test_12 values (1, '少年张三丰');
2022-01-04 14:27:14.075 CST [3010] ERROR:  input value too long for type nvarchar2(5 byte)
2022-01-04 14:27:14.075 CST [3010] STATEMENT:  insert into test_12 values (1, '少年张三丰');
ERROR:  input value too long for type nvarchar2(5 byte)

### Expected behavior/code
select '我是一个中国人'::char(5);
 bpchar
--------
 我
(1 row)

insert into test_12 values (1, '少年张三丰'); --expect succ
### Step to reproduce
set nls_length_semantics to byte ;
select '我是一个中国人'::char(5);

create  table test_12 (id int, a oracle.nvarchar2(5));
insert into test_12 values (1, 'abcde');
insert into test_12 values (1, '少年张三丰');

### Additional context that can be helpful for identifying the problem
1. Explicit conversion should output the most suitable string.
2. nvarchar2 does not distinguish between byte and char.

**Comment by BingAo-Office** [comment]
Hi, AndyQinshy
       Thank you for using and suggestion! This problem resolved by #37. welcome to review our code!

**Comment by AndyQinshy** [comment]
thans, I use the latest code and found this bug has been fixed。
