### ISSUE TITLE
make oracle-installcheck fail

### ISSUE THREAD

**Issue by tanyang-star** [IvorySQL/IvorySQL#348]
## Bug Report
make oracle-installcheck fail

### IvorySQL Version
IvorySQL master

### OS Version (uname -a)
centOS 7

### Current Behavior
make oracle-installcheck fail
![image](https://github.com/IvorySQL/IvorySQL/assets/92354960/0a6a347d-77f9-435e-b702-b8d33a60d75a)

### Expected behavior/code
Success

### Step to reproduce
pg_ctl ../data start
make oracle-installcheck

**Comment by DutMsn** [comment]
#542 #543
