### ISSUE TITLE
binary_double/binary_float 对数据校验有误

### ISSUE THREAD

**Issue by tanyang-star** [IvorySQL/IvorySQL#376]
## Bug Report
binary_double/binary_float 对数据校验有误

### IvorySQL Version
IvorySQL master

### OS Version (uname -a)
CentOS 7

### Current Behavior
问题1：

ivorysql不支持D/d F/f科学计数法，但在oracle中F/f D/d分别表示该数字是binary_float/binary_double,若省略以上关键字则该数字类型为number

问题2：

以下是去掉D/d F/f 涉及到的插入数据的范围和显示问题(推测与number范围有关)

binary_float：

``` sql
create table binaryf_tb(binaryf_clo binary_float);

1)insert into binaryf_tb values(3.40282E 38);
2)insert into binaryf_tb values(3.40282E 39);
3)insert into binaryf_tb values(3.40283E 38); 
4)insert into binaryf_tb values(-3.40282E 38); 
5)insert into binaryf_tb values(-3.40283E 38); 
6)insert into binaryf_tb values(-3.40282E 39);
```

【结果】

  1)插入成功,查询数据为3.403e 38
   2)插入失败，超出范围(不追加F/f,默认传入数字类型为number,超出最大范围值取无穷大)
   3)插入失败，超出范围(不追加F/f,默认传入数字类型为number,超出最大范围值取无穷大)
   4)插入成功,查询数据为-3.4E 38
   5)插入失败，超出范围
   6)插入失败，超出范围

binary_double：

``` sql
create table binaryf_tb(binaryf_clo binary_double);

1)insert into binaryd_tb values(2.22507485850720E-308);
2)insert into binaryd_tb values(2.22507485850720E-309);
3)insert into binaryd_tb values(2.22507485850721E 308); 
4)insert into binaryd_tb values(-2.22507485850720E-308); 
5)insert into binaryd_tb values(-2.22507485850721E-308); 
6)insert into binaryd_tb values(-2.22507485850720E 309);
```

【结果】

   1)插入成功,查询数据为2.225e-308
   2)插入成功,查询数据为2.225e-309
   3)插入失败,超出范围
   4)插入成功,查询数据为-2.225e-308
   5)插入成功,查询数据为-2.225e-309
   6)插入失败,超出范围

### Expected behavior/code

binary_float：
【期望】

   1)插入成功,查询数据为3.403E 038
   2)插入成功,查询数据为Inf(不追加F/f,默认传入数字类型为number,超出最大范围值取无穷大)
   3)插入成功,查询数据为Inf(不追加F/f,默认传入数字类型为number,超出最大范围值取无穷大)
   4)插入成功,查询数据为-3.4E 038
   5)插入成功,查询数据为-Inf
   6)插入成功,查询数据为-Inf

binary_double：
【期望】

   1)插入成功,查询数据为0
   2)插入成功,查询数据为0
   3)插入失败,超出范围
   4)插入成功,查询数据为0
   5)插入成功,查询数据为0
   6)插入失败,超出范围

**Comment by LiuZheng7** [comment]
For testing, please ignore.
