### ISSUE TITLE
ERROR:  syntax error at or near "1"

### ISSUE THREAD

**Issue by jonedaniel1** [IvorySQL/IvorySQL#421]
## Bug Report
ERROR:  syntax error at or near "1"

### IvorySQL Version
2.3/2.2

### OS Version (uname -a)
Docker CentOS 7

### Configuration options  ( config.status --config )
postgres（default）

### Current Behavior
Backup file can't recover

### Expected behavior/code
pg_dump dbname > xxx.sql
psql dbname < xxx.sql
Error

### Additional context that can be helpful for identifying the problem

![image](https://github.com/IvorySQL/IvorySQL/assets/22540803/e56b83f1-10a1-4770-94fc-d48031341cf6)

COPY public.account_account (id, message_main_attachment_id, currency_id, company_id, group_id, root_id, create_uid, write_uid, name, code, account_type, internal_group, note, deprecat
ed, include_initial_balance, reconcile, is_off_balance, non_trade, create_date, write_date) FROM stdin;
1       \N      \N      1       \N      49048   1       1       {"en_US": "流动性转移", "zh_CN": "流动性转移"}  101201  asset_current   asset   \N      f       t       t       f       f       2023-08-09 03:54:05.58827       2023-08-09 03:54:05.58827
7       \N      \N      1       \N      49049   1       1       {"en_US": "Accounts Receivable (PoS)", "zh_CN": "Accounts Receivable (PoS)"}    112400  asset_receivable        asset   \N      f       t       t       f       f       2023-08-09 03:54:05.58827       2023-08-09 03:54:05.58827
78      \N      \N      1       \N      57057   1       1       {"en_US": "现金折扣损失", "zh_CN": "现金折扣损失"}      999998  expense expense \N      f       f       f       f       f       2023-08-09 03:54:05.58827       2023-08-09 03:54:05.58827
79      \N      \N      1       \N      57057   1       1       {"en_US": "现金折扣收益", "zh_CN": "现金折扣收益"}      999997  income_other    income  \N      f       f       f       f       f       2023-08-09 03:54:05.58827       2023-08-09 03:54:05.58827
80      \N      \N      1       \N      49048   1       1       {"en_US": "银行搁置科目", "zh_CN": "银行搁置科目"}      100201  asset_current   asset   \N      f       t       f       f       f       2023-08-09 03:54:05.58827       2023-08-09 03:54:05.58827
81      \N      \N      1       \N      49048   1       1       {"en_US": "未完成收据", "zh_CN": "未完成收据"}  100202  asset_current   asset   \N      f       t       t       f       f       2023-08-09 03:54:05.58827       2023-08-09 03:54:05.58827
82      \N      \N      1       \N      49048   1       1       {"en_US": "未完成款项", "zh_CN": "未完成款项"}  100203  asset_current   asset   \N      f       t       t       f       f       2023-08-09 03:54:05.58827       2023-08-09 03:54:05.58827
83      \N      \N      1       \N      57057   1       1       {"en_US": "现金差额损失", "zh_CN": "现金差额损失"}      999001  expense expense \N      f       f       f       f       f       2023-08-09 03:54:05.58827       2023-08-09 03:54:05.58827
84      \N      \N      1       \N      57057   1       1       {"en_US": "现金差价收益", "zh_CN": "现金差价收益"}      999002  income_other    income  \N      f       f       f       f       f       2023-08-09 03:54:05.58827       2023-08-09 03:54:05.58827
85      \N      \N      1       \N      49048   1       1       {"en_US": "现金", "zh_CN": "现金"}      100101  asset_cash      asset   \N      f       t       f       f       f

**Comment by tanyang-star** [comment]
能否提供account_account 表的创建语句，才能复现

**Comment by jonedaniel1** [comment]
建表SQL参见附件。。
主要错误是：
通过pg_dump备份的文件，
在通过psql进行恢复的时候，报语法错误。。
















在 2023-08-10 09:41:46，"tanyang-star" ***@***.***> 写道：

能否提供account_account 表的创建语句，才能复现

**Comment by jonedaniel1** [comment]
[account_account.txt](https://github.com/IvorySQL/IvorySQL/files/12309154/account_account.txt)
建表SQL见附件；另外，使用pg_dump备份的文件在postgreSQL 14.2的版本上可以使用psql还原。

**Comment by tanyang-star** [comment]
是否应该设置兼容模式为pg模式，然后试一下?参数为：compatible_mode

**Comment by DutMsn** [comment]
可以确认一下COPY的字段是否用tab作为分隔符，以下为tab分隔符的结果
![image](https://github.com/IvorySQL/IvorySQL/assets/41883314/087420b8-7711-4218-89f4-efb9933ca913)
如果使用空格作为分隔符，会报语法错误，如下
![image](https://github.com/IvorySQL/IvorySQL/assets/41883314/365fb0a8-436b-461b-81a6-a10ad874d777)

**Comment by DutMsn** [comment]
我们无法复现出这种语法错误，可以给一份更详细的用例吗
