### ISSUE TITLE
日期格式中的DD HH.MI,SS AM中数据出现特殊符号后的数据处理与Oracle不一致

### ISSUE THREAD

**Issue by tanyang-star** [IvorySQL/IvorySQL#435]
## Bug Report
日期格式中的DD HH.MI,SS AM中数据出现特殊符号后的数据处理与Oracle不一致

### IvorySQL Version
IvorySQL master

### OS Version (uname -a)
CentOS 7

### Current Behavior
DD:
![image](https://github.com/IvorySQL/IvorySQL/assets/92354960/4c8773fc-10b9-483d-ac0b-33bf22b9ab9f)
HH:
![image](https://github.com/IvorySQL/IvorySQL/assets/92354960/fd682327-c070-46c0-910b-98ab831a8657)
MI:
![image](https://github.com/IvorySQL/IvorySQL/assets/92354960/a3c7e1e2-d1f2-4f0a-b975-ec4d7fe8d05b)
SS:
![image](https://github.com/IvorySQL/IvorySQL/assets/92354960/e971c5a7-d791-411d-889c-108837fe758d)
FF:
![image](https://github.com/IvorySQL/IvorySQL/assets/92354960/851b6574-0bea-4db8-b7fa-97967bbcf53b)
混合符号:
![image](https://github.com/IvorySQL/IvorySQL/assets/92354960/8fc22a3d-74a3-44b9-9004-f0d923d2b7e3)
![image](https://github.com/IvorySQL/IvorySQL/assets/92354960/b66003a0-122a-4c22-a971-258c6aa09c2e)
### Expected behavior/code
应兼容oracle校验规则

**Comment by DutMsn** [comment]
#459
