### ISSUE TITLE
IvorySQL PL/SQL  创建函数/存储过程存在问题 

### ISSUE THREAD

**Issue by Z-xm99** [IvorySQL/IvorySQL#477]
## Bug Report
plisql 创建函数/存储过程存在问题 

### IvorySQL Version
IvorySQL master

### OS Version (uname -a)
CentOS -8

### Configuration options  ( config.status --config )
set ivorysql.compatible_mode = oracle;

### Current Behavior
1、感觉词法处理不到位 不能消化/  后续变成-  不能结束的状态
```plsql
create or replace function ftest return int as  
begin
return 25;
end;
/
``` 
结果如图：
![3853244cd0faea4bca36bf4c3f32638](https://github.com/IvorySQL/IvorySQL/assets/69310610/13702093-7f3d-4a79-a074-54346bd234f8)

2、 在原先的基础上 声明了一个变量 va  ，可能需要检查语法文件和词法文件
```plsql
create or replace function ftest return int 
as
va int;  
begin
return 25;
end;
/
``` 
结果如图：
![1fed2eeabafc6dd360ba11816e49cf1](https://github.com/IvorySQL/IvorySQL/assets/69310610/51be7aea-e0ec-40c9-bef3-e93307abb359)

3、触发了一次 后续没有再碰到  这个就更有意思了 复制粘贴正常运行 能消耗'/ '并且创建成功,但是按上建 or replace会陷入不能结束的状态
![6e366b535df8a6d02afd4ead69ac67e](https://github.com/IvorySQL/IvorySQL/assets/69310610/a54128bb-f5db-45e6-a22b-839e8a66bcb5)

### Expected behavior/code
正常创建

### Step to reproduce
如上所示

**Comment by Z-xm99** [comment]
第一种情况 其实不改也没啥事 其实就和EDB一样

**Comment by wangjie-star** [comment]
感谢您提的问题，针对第一个问题，我们是已经解决了的，具体用法如下：
![1693449009603](https://github.com/IvorySQL/IvorySQL/assets/116478190/cef4f750-b4be-417e-b6e6-51c2062fdef6)

**Comment by Z-xm99** [comment]
> 感谢您提的问题，针对第一个问题，我们是已经解决了的，具体用法如下： ![1693449009603](https://user-images.githubusercontent.com/116478190/264517556-cef4f750-b4be-417e-b6e6-51c2062fdef6.png)

盲猜一嘴 这也许是在psql层面配合语法文件实现的隐含参数 。 想请问关于ivorysql内置的隐含参数 由具体文档链接提供吗  没这些东西的话 比如说此处的**\parser** 对于初来乍到的开发人员来说属实有些痛苦

**Comment by wangjie-star** [comment]
> 
目前暂时没有相关文档，后续会补充相关文档到IvorySQL官网

**Comment by Z-xm99** [comment]
I will choose this.
