### ISSUE TITLE
Some test case failed about dual table

### ISSUE THREAD

**Issue by Outsider0413** [IvorySQL/IvorySQL#482]
## Bug Report
oracle-pg-check error in opr_sanity.sql
![image](https://github.com/IvorySQL/IvorySQL/assets/130623271/3018a4bd-da20-4482-8671-b0874d3d6382)

### IvorySQL Version
master
### OS Version (uname -a)
CentOS 7
### Configuration options  ( config.status --config )
./configure --prefix=$PWD/inst --enable-cassert --enable-debug --enable-tap-tests --enable-rpath --with-tcl --with-python --with-gssapi --with-pam --with-ldap --with-openssl --with-libedit-preferred --with-uuid=e2fs --with-ossp-uuid --with-libxml --with-libxslt --with-perl --with-icu CFLAGS='-DGCC_HASCLASSVISIBILITY -O0 -Wall -W -g3 -gdwarf-2'
### Current Behavior
![image](https://github.com/IvorySQL/IvorySQL/assets/130623271/e37bb011-ba0d-4255-ae95-4053b6c05ace)

### Expected behavior/code
![image](https://github.com/IvorySQL/IvorySQL/assets/130623271/d737c355-cc47-4f6f-9a67-73bbf53a34da)

### Step to reproduce
./configure --prefix=$PWD/inst --enable-cassert --enable-debug --enable-tap-tests --enable-rpath --with-tcl --with-python --with-gssapi --with-pam --with-ldap --with-openssl --with-libedit-preferred --with-uuid=e2fs --with-ossp-uuid --with-libxml --with-libxslt --with-perl --with-icu CFLAGS='-DGCC_HASCLASSVISIBILITY -O0 -Wall -W -g3 -gdwarf-2'
make
make oracle-pg-check

**Comment by DutMsn** [comment]
Maybe the expected output is correct, and we hope to get this.
