### ISSUE TITLE
There was an error while restoring the backup

### ISSUE THREAD

**Issue by Outsider0413** [IvorySQL/IvorySQL#483]
## Bug Report
After creating a table with the column attribute pg_catalog.varchar in Oracle mode, the type after restoring through pg_dump backup is inconsistent.
### IvorySQL Version
master
### OS Version (uname -a)
CentOS 7
### Configuration options  ( config.status --config )
./configure --prefix=$PWD/inst --enable-cassert --enable-debug --enable-tap-tests --enable-rpath --with-tcl --with-python --with-gssapi --with-pam --with-ldap --with-openssl --with-libedit-preferred --with-uuid=e2fs --with-ossp-uuid --with-libxml --with-libxslt --with-perl --with-icu CFLAGS='-DGCC_HASCLASSVISIBILITY -O0 -Wall -W -g3 -gdwarf-2'
### Current Behavior
![image](https://github.com/IvorySQL/IvorySQL/assets/130623271/fd150b08-dac5-4ec4-a100-f582f6f9ede0)
./pg_dump -dpostgres -p1521 > 1.sql
![image](https://github.com/IvorySQL/IvorySQL/assets/130623271/8a15ec1f-61d3-47d2-995a-f2d30fca394b)
./createdb test
./psql -dtest -p1521 < 1.sql
![image](https://github.com/IvorySQL/IvorySQL/assets/130623271/59d84537-8233-48ae-a6dd-f4c47ab658c1)

### Expected behavior/code
The data type after restoration should be the same as before
### Step to reproduce
./configure --prefix=$PWD/inst --enable-cassert --enable-debug --enable-tap-tests --enable-rpath --with-tcl --with-python --with-gssapi --with-pam --with-ldap --with-openssl --with-libedit-preferred --with-uuid=e2fs --with-ossp-uuid --with-libxml --with-libxslt --with-perl --with-icu CFLAGS='-DGCC_HASCLASSVISIBILITY -O0 -Wall -W -g3 -gdwarf-2'
make
make install
./initdb -D ../data
./pg_ctl -D ../data -l ../logfile start
./createdb test
./psql -dpostgre -p1521
create table test(a pg_catalog.varchar);
./pg_dump -dpostgre -p1521 > 1.sql
./psql -dtest -p1521 < 1.sql

**Comment by Outsider0413** [comment]
#485

**Comment by DutMsn** [comment]
This issue has been resolved in PR #494 .
