### ISSUE TITLE
call wrong function

### ISSUE THREAD

**Issue by tanyang-star** [IvorySQL/IvorySQL#486]
## Bug Report
当兼容模式下，schema和sys存在同名函数，且参数个数相同。唯一的区别是pg_catalog下是数据类型为text。sys下数据类型为varchar2。调用函数时会选择text数据类型

### IvorySQL Version
IvorySQL 3.0

### OS Version (uname -a)
CentOS 7

### Current Behavior
![image](https://github.com/IvorySQL/IvorySQL/assets/92354960/b613dae7-3b9a-40f7-93ee-f6eefe67d864)

### Expected behavior/code
call sys.fun(....)

**Comment by Z-xm99** [comment]
请问IvorySQL 3.0 是哪个分支呀

**Comment by grantzhou** [comment]
> 请问IvorySQL 3.0 是哪个分支呀

3.0就是默认的Master分支，目前正在开发中，将在年底合并PG16后发布
