### ISSUE TITLE
call sys.length('今天')  fail

### ISSUE THREAD

**Issue by tanyang-star** [IvorySQL/IvorySQL#489]
## Bug Report
call sys.length('今天')  fail

### IvorySQL Version
IvorySQL master

### OS Version (uname -a)
CentOS 7

### Current Behavior
![image](https://github.com/IvorySQL/IvorySQL/assets/92354960/a38129f3-5dc8-42bc-96e9-3cc2f8c577c0)

### Expected behavior/code
success

### Step to reproduce
./psql -U ty -d postgres -p 1521

postgres=# select sys.length('今天') from dual;

**Comment by Z-xm99** [comment]
CREATE OR REPLACE FUNCTION sys.length(text)
 RETURNS integer
 LANGUAGE internal
 IMMUTABLE PARALLEL SAFE STRICT
AS $function$textlen$function$; 试试这个 @tanyang-star

**Comment by Z-xm99** [comment]
![image](https://github.com/IvorySQL/IvorySQL/assets/69310610/5c200efd-915d-4fbb-a82a-b376b7844f04)

**Comment by Z-xm99** [comment]
![image](https://github.com/IvorySQL/IvorySQL/assets/69310610/e14daf76-87e6-4798-9e40-a1175e6f913c)
