### ISSUE TITLE
make oracle-check tests failed

### ISSUE THREAD

**Issue by Z-xm99** [IvorySQL/IvorySQL#527]
## Bug Report
![image](https://github.com/IvorySQL/IvorySQL/assets/69310610/94ae540b-b8af-4566-99f3-a72b23da9e03)
![image](https://github.com/IvorySQL/IvorySQL/assets/69310610/d8d1f6c7-3213-481b-9d84-6fad89d7933d)

### IvorySQL Version
master
* master 3ce85425bd update action

### OS Version (uname -a)
Linux halo-centos-8-release 4.18.0-305.3.1.el8.x86_64 #1 SMP Tue Jun 1 16:14:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior
cd src/oracle_test/
make oracle-check

### Expected behavior/code
tests passed.

**Comment by DutMsn** [comment]
Thank you for your test, we will fix this bug right now.

**Comment by DutMsn** [comment]
#532 #533 
Maybe there are some bugs like this issue, so we will open this issue for PR in the future
