### ISSUE TITLE
The output result is different from oracle，00979. 00000 -  "not a GROUP BY expression"

### ISSUE THREAD

**Issue by Huajianjin** [IvorySQL/IvorySQL#548]
## Bug Report

00979. 00000 -  "not a GROUP BY expression"

### IvorySQL Version

3.0

### OS Version (uname -a)

Linux localhost.localdomain 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Configuration options  ( config.status --config )

./configure --prefix=/home/IVORYSQL --enable-debug --enable-cassert CFLAGS='-O0 -g' --enable-tap-tests

### Current Behavior

./initdb -D data -m oracle
./pg_ctl -D data start
./psql -p1521 postgres
create table test(id int primary key,name varchar(20));
insert into test values(1,'a');
insert into test values(2,'b');
select name from test group by id;
name
------
 b
 a
(2 rows)

### Expected behavior/code

ORA-00979: 不是 GROUP BY 表达式
00979. 00000 -  "not a GROUP BY expression"

### Step to reproduce
create table test(id int primary key,name varchar(20));
insert into test values(1,'a');
insert into test values(2,'b');
select name from test group by id;

**Comment by tanyang-star** [comment]
I  think so 。
