### ISSUE TITLE
ivorysql 3, invalid zero OID reference

### ISSUE THREAD

**Issue by shawn0915** [IvorySQL/IvorySQL#550]
### IvorySQL Version
IVORY_REL_3_STABLE

### OS Version (uname -a)
[root@rocky9 IvorySQL-Ivorysql_3.0_Beta]# uname -a
Linux rocky9.shawnyan.cn 5.14.0-284.30.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Sep 16 09:55:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior
invalid zero OID reference in pg_type.dat field typinput line 702

![图片](https://github.com/IvorySQL/IvorySQL/assets/17957066/8533da2e-283b-41f4-90f7-75a852964703)

### Step to reproduce
编译make的时候，报了这些warn，是符合预期的状态么？

**Comment by DutMsn** [comment]
这个问题是之前引入的问题，不会影响使用，在执行make clean过后，第二次编译就不会出现这些信息。
我们暂时不会去消除这些警告信息。

**Comment by shawn0915** [comment]
@DutMsn 了解，感谢回复。
