### ISSUE TITLE
ivorysql 3, confusing about make install output

### ISSUE THREAD

**Issue by shawn0915** [IvorySQL/IvorySQL#553]
### IvorySQL Version
IvorySQL-Ivorysql_3.0_Beta
### Current Behavior
make install 的时候,这些都会输出两次，令人困惑。
![图片](https://github.com/IvorySQL/IvorySQL/assets/17957066/2a843848-9e2b-4480-a553-84de2d391ab4)

**Comment by tanyang-star** [comment]
![image](https://github.com/IvorySQL/IvorySQL/assets/92354960/141302f0-00af-4ef0-9c53-16439c247977)
postgres was originally the same as this
