### ISSUE TITLE
missing params in settings table

### ISSUE THREAD

**Issue by shawn0915** [IvorySQL/IvorySQL#556]
### IvorySQL Version
3.0
### Current Behavior
```
ivorysql=# select name,setting,short_desc from pg_settings where name like '%ivory%';
                name                 |   setting   |                              short_desc                              
-------------------------------------+-------------+----------------------------------------------------------------------
 ivorysql.compatible_mode            | pg          | Set default sql parser compatibility mode
 ivorysql.database_mode              | pg          | Set database mode
 ivorysql.datetime_ignore_nls_mask   | 0           | Sets the datetime type input is not controlled by the NLS parameter.
 ivorysql.enable_emptystring_to_NULL | off         | whether convert empty string to NULL.
 ivorysql.identifier_case_switch     | interchange | Set character case conversion mode.
 ivorysql.listen_addresses           | localhost   | Sets oracle host name or IP address(es) to listen to.
 ivorysql.port                       | 1521        | Sets the Oracle TCP port the server listens on.
(7 rows)
```

doesn't exists `ivorysql.enable_case_switch` ?

**Comment by DutMsn** [comment]
This parameter is used to control whether to enable the case control function in Oracle mode. We believe that this parameter should not be displayed for users in Oracle mode. It is for developers. @shawn0915

**Comment by shawn0915** [comment]
@DutMsn 
thank u for your reply.
about this case, users can be set by themselves, 
```
ivorysql=# set ivorysql.enable_case_switch=off;
SET
ivorysql=# CREATE TABLE "ABCD"(c1 int, c2 int);
CREATE TABLE
ivorysql=# SELECT relname FROM pg_class WHERE relname = 'ABCD';
 relname
---------
 ABCD
(1 row)

ivorysql=# SELECT relname FROM pg_class WHERE relname = 'abcd';
 relname
---------
(0 rows)

ivorysql=# show ivorysql.database_mode ;
 ivorysql.database_mode
------------------------
 oracle
(1 row)
```

**Comment by DutMsn** [comment]
> @DutMsn thank u for your reply. about this case, users can be set by themselves,
> 
> ```
> ivorysql=# set ivorysql.enable_case_switch=off;
> SET
> ivorysql=# CREATE TABLE "ABCD"(c1 int, c2 int);
> CREATE TABLE
> ivorysql=# SELECT relname FROM pg_class WHERE relname = 'ABCD';
>  relname
> ---------
>  ABCD
> (1 row)
> 
> ivorysql=# SELECT relname FROM pg_class WHERE relname = 'abcd';
>  relname
> ---------
> (0 rows)
> 
> ivorysql=# show ivorysql.database_mode ;
>  ivorysql.database_mode
> ------------------------
>  oracle
> (1 row)
> ```

Yeah, this parameter can be set by user. 
First, the user should have no way of knowing this parameter except by reading the source code. Secondly, this parameter will change the function of `ivorysql.identifier_case_switch`.
If you pay attention to the regression testing, you will find that we have three sets of tests， namely `check`, `oracle-check`, `oracle-pg-check`. Keep this parameter so that it can be set and will not be shown by the user in order to execute `oracle-pg-check`. This ensures that the changes we make will not affect the original functionality of PG.

**Comment by shawn0915** [comment]
@DutMsn thx for ur reply, that's make sense.
