### ISSUE TITLE
oracle模式下，字段长度不兼容

### ISSUE THREAD

**Issue by shawn0915** [IvorySQL/IvorySQL#561]
### IvorySQL Version
IvorySQL 3.0 BETA

### Current Behavior

- char

ivorysql，可以创建表，并定义字段为`char(2001)`

```
ivorysql=# \parser
Oracle parser.
ivorysql=# create table t_char(a char(1), b char(2000), c char(2001));
CREATE TABLE
```

但是在oracle报错
```
SQL*Plus: Release 19.0.0.0.0 - Production on Tue Aug 30 00:00:19 2022
Version 19.6.0.0.0

00:03:06 localhost:SQL>create table t_char(a char(1), b char(2000), c char(2001));
create table t_char(a char(1), b char(2000), c char(2001))
                                                    *
ERROR at line 1:
ORA-00910: specified length too long for its datatype
```

- timestamp

ivorysql，创建表，并定义字段为`timestamp(9)`时，报warning

```
ivorysql=# \parser
Oracle parser.
ivorysql=# create table t_timestamp(a timestamp, b timestamp(0), c timestamp(6), d timestamp(9));
WARNING:  TIMESTAMP(9) effective number of fractional seconds is 6,the part of excess is 0
LINE 1: ...mp(a timestamp, b timestamp(0), c timestamp(6), d timestamp(...
                                                             ^
WARNING:  TIMESTAMP(9) effective number of fractional seconds is 6,the part of excess is 0
CREATE TABLE
ivorysql=#
```

但是在oracle可以正常创建

```
00:02:49 localhost:SQL>create table t_timestamp(a timestamp, b timestamp(0), c timestamp(6), d timestamp(9));

Table created.
```

**Comment by DutMsn** [comment]
> ## Bug Report
> ### IvorySQL Version
> IvorySQL 3.0 BETA
> 
> ### OS Version (uname -a)
> ### Configuration options ( config.status --config )
> ### Current Behavior
> * char
> 
> ivorysql，可以创建表，并定义字段为`char(2001)`
> 
> ```
> ivorysql=# \parser
> Oracle parser.
> ivorysql=# create table t_char(a char(1), b char(2000), c char(2001));
> CREATE TABLE
> ```
> 
> 但是在oracle报错
> 
> ```
> SQL*Plus: Release 19.0.0.0.0 - Production on Tue Aug 30 00:00:19 2022
> Version 19.6.0.0.0
> 
> 00:03:06 localhost:SQL>create table t_char(a char(1), b char(2000), c char(2001));
> create table t_char(a char(1), b char(2000), c char(2001))
>                                                     *
> ERROR at line 1:
> ORA-00910: specified length too long for its datatype
> ```
> 
> * timestamp
> 
> ivorysql，创建表，并定义字段为`timestamp(9)`时，报warning
> 
> ```
> ivorysql=# \parser
> Oracle parser.
> ivorysql=# create table t_timestamp(a timestamp, b timestamp(0), c timestamp(6), d timestamp(9));
> WARNING:  TIMESTAMP(9) effective number of fractional seconds is 6,the part of excess is 0
> LINE 1: ...mp(a timestamp, b timestamp(0), c timestamp(6), d timestamp(...
>                                                              ^
> WARNING:  TIMESTAMP(9) effective number of fractional seconds is 6,the part of excess is 0
> CREATE TABLE
> ivorysql=#
> ```
> 
> 但是在oracle可以正常创建
> 
> ```
> 00:02:49 localhost:SQL>create table t_timestamp(a timestamp, b timestamp(0), c timestamp(6), d timestamp(9));
> 
> Table created.
> ```
> 
> ### Expected behavior/code
> ### Step to reproduce
> ### Additional context that can be helpful for identifying the problem

关于问题一，后续可能会针对这个问题做出修复
关于问题二，因为我们在实现Oracle的数据类型时，采用的仍然是PG的内存结构，因此timestamp的精度只能设置6位，超过6位精度的时间会进行四舍五入之后存储

**Comment by shawn0915** [comment]
@DutMsn 谢谢回复。
Q1: thank u.
Q2: 了解，如果有必要，还是在文档中说明一下会更好。

**Comment by bigplaice** [comment]
This issue has been addressed by PR 691&692: 
https://github.com/IvorySQL/IvorySQL/pull/692

**Comment by bigplaice** [comment]
This issue has been addressed by PR 691&692:
https://github.com/IvorySQL/IvorySQL/pull/691
https://github.com/IvorySQL/IvorySQL/pull/692
