### ISSUE TITLE
Schedule of add missed functionalities of 3.0 and why orafce been removed?

### ISSUE THREAD

**Issue by lomatus** [IvorySQL/IvorySQL#572]
## Enhancement

When 3.0 migrated to the new architecture, some features were supported in 2.3 but not in 3.0, do you have a planned timeline to reappear these features if end users want to upgrade to 3.0?

When orafce is removed, do you plan to refactor features based on the new architecture?

**Comment by tanyang-star** [comment]
Version 3.0 has major architectural adjustments. oraface not applicable
