### ISSUE TITLE
psql -p 5432 报错

### ISSUE THREAD

**Issue by tanyang-star** [IvorySQL/IvorySQL#575]
## Bug Report
连接IvorySQL数据库默认的数据库是ivorysql，当前的IvorySQL 3.0 版initdb的时候只创建了postgres数据库，没有创建ivorysql数据库。报错
### IvorySQL Version
IvorySQL beta 3.0

### OS Version (uname -a)
CentOS 7

### Current Behavior
![image](https://github.com/IvorySQL/IvorySQL/assets/92354960/8222cad9-2685-401f-befc-e6bf7325665b)

### Expected behavior/code
成功

**Comment by tanyang-star** [comment]
感谢IvorySQL爱好者发现的这个问题。我在这里整理成issue

**Comment by gaoxueyu** [comment]
issue fixe by PR [https://github.com/IvorySQL/IvorySQL/pull/625](url) at version 3.1

**Comment by gaoxueyu** [comment]
Issue has been fixed at IvorySQL 3.1
