### ISSUE TITLE
怎么切换oralce模式

### ISSUE THREAD

**Issue by adonis2014** [IvorySQL/IvorySQL#579]
### IvorySQL Version
3.0
### Additional context that can be helpful for identifying the problem
ivorysql=# \parser ORACLE
PG parser.
\parser: extra argument "ORACLE" ignored
ivorysql=# \parser
PG parser.
ivorysql=# set compatible_mode = oracle;
ERROR:  unrecognized configuration parameter "compatible_mode"
ivorysql=#

**Comment by zhanghongyuan111** [comment]
感谢反馈，如果要切换为Oracle模式，set ivorysql.compatible_mode=oracle;
