### ISSUE TITLE
兼容oracle中的类型，不能在sql工具中指定长度

### ISSUE THREAD

**Issue by adonis2014** [IvorySQL/IvorySQL#581]
### Additional context that can be helpful for identifying the problem
![1701309160735](https://github.com/IvorySQL/IvorySQL/assets/8855523/a31b946f-2891-4649-b51b-c161126ce8b5)

**Comment by LiuZheng7** [comment]
@adonis2014 您好，我是IvorySQL社区维护人员，感谢您为项目建设做出的贡献，社区拟为您颁发贡献奖杯，请添加微信IvorySQL_official或通过邮箱ivorysql@highgo.com与我们取得联系，期待您的回复。
