### ISSUE TITLE
oralce模式下sysdate时间格式不对,缺少时分秒

### ISSUE THREAD

**Issue by adonis2014** [IvorySQL/IvorySQL#582]
### Additional context that can be helpful for identifying the problem
oracle 
select sysdate from dual;
2023-11-30 13:55:59.000
IvorySQL 3.0
select sysdate from dual;
2023-11-30

**Comment by zhanghongyuan111** [comment]
感谢您的反馈，IvorySQL3.0版本的sysdate函数，默认情况下select 只显示年月日，如果您想要显示时分秒，请在查询sql前执行alter session set NLS_DATE_FORMAT='YYYY-MM-RR HH24:MI:SS';

**Comment by LiuZheng7** [comment]
@adonis2014  您好，我是IvorySQL社区维护人员，感谢您为项目建设做出的贡献，社区拟为您颁发贡献奖杯，请添加微信IvorySQL_official或通过邮箱ivorysql@highgo.com与我们取得联系，期待您的回复。
