### ISSUE TITLE
IvorySQL1.1 build failed under Windows11 

### ISSUE THREAD

**Issue by liuxintang** [IvorySQL/IvorySQL#60]
## Bug Report
Copying pg_config_os.h...
Generating configuration headers...
undefined symbol: PACKAGE_IVORYSQL_VERSION at src/include/pg_config.h line 795 at H:/VisualProject/vs2019/IvorySQL/IvorySQL-Ivory_REL_1_1/src/tools/msvc/Mkvcbuild.pm line 864.
### IvorySQL Version
1.1
### OS Version (uname -a)
Windows11
visual studio 2019
### Configuration options  ( config.status --config )
H:\VisualProject\vs2019\IvorySQL\IvorySQL-Ivory_REL_1_1\src\tools\msvc>perl build.pl DEBUG

**Comment by BingAo-Office** [comment]
At present, no adaptation has been made on Windows. In the future, the community will arrange adaptation according to the actual situation
Thanks for your using!

**Comment by liuxintang** [comment]
Hi @BingAo-Office 
Understand, thanks!
