### ISSUE TITLE
New feature：Support searching and downloading PDF documents

### ISSUE THREAD

**Issue by gaoxueyu** [IvorySQL/IvorySQL#622]
## Feature Request - Search and download pdf documents

**Add a new feature to support searching and downloading PDF documents instead of online mode.
This feature can greatly increase user experience.
You can browse documents online and save PDF documents directly.**

**Comment by balinorLiang** [comment]
The documentation issue could be closed and re-created in [ivory-doc-builder](https://github.com/balinorLiang/ivory-doc-builder).And search feature has been finished in PR [Add search feature](https://github.com/IvorySQL/ivory-doc-builder/pulls)，then [Global Text Search](https://github.com/IvorySQL/ivory-doc-builder/issues/6) also mentioned search feature. We could close this issue, and create a new issue which is related with Download feature. FYI.

**Comment by gaoxueyu** [comment]
Same with https://github.com/IvorySQL/ivory-doc-builder/issues/6.
pdf has been done via https://github.com/IvorySQL/ivorysql_web/pull/75.
