### ISSUE TITLE
Default SYSDATE couldn't be used in Oracle mode

### ISSUE THREAD

**Issue by balinorLiang** [IvorySQL/IvorySQL#633]
When I create table with SYSDATE in IvorySQL 3.0, DB will report error. However, the error wouldn't be reported in IvorySQL 2.3
Example:
```
CREATE TABLE CRM_CON
(
SIGN_TIME DATE DEFAULT SYSDATE
NOT NULL
);
```
Error:
```
ERROR: cannot use column reference in DEFAULT expression
Line 3: SIGN_TIME DATE DEFAULT SYSDATE
```

**Comment by gaoxueyu** [comment]
Issue has been fixed by #663  and will be included in Release 3.3.
