### ISSUE TITLE
希望补充 ivorysql.datetime_ignore_nls_mask 相关测试用例

### ISSUE THREAD

**Issue by shawn0915** [IvorySQL/IvorySQL#634]
## Enhancement

文档中简述了该参数的功能，但在实测中并没发现该如何正确使用它，希望补充一些测试用例，以供参考。

**Comment by balinorLiang** [comment]
I couldn't agree more !!!
For this enhancement, I created a PR with one commit in [IvorySQL docs project](https://github.com/IvorySQL/ivorysql_docs/pull/66/commits/d7f75b5ce19c26d8aa2115b76319e5676219e7a8)
If you have any suggestion, welcome to leave comments in my commit, thanks a lot @shawn0915

**Comment by balinorLiang** [comment]
https://docs.ivorysql.org/en/ivorysql-doc/v3.2/v3.2/15#ivorysql-datetime_ignore_nls_mask

**Comment by balinorLiang** [comment]
We will add some test cases in IvorySQL oracle regression test

**Comment by balinorLiang** [comment]
Some datetime_ignore_nls_mask test cases have been added into [IVORY_REL_3_STABLE](https://github.com/IvorySQL/IvorySQL/tree/IVORY_REL_3_STABLE), the PR is #656. 
Issue is closed now.
