### ISSUE TITLE
IvorySQL3.1 incorrect version number

### ISSUE THREAD

**Issue by elodiefb** [IvorySQL/IvorySQL#636]
The version number of IvorySQL3.1 is incorrect, now shown as 3.0:
 
postgres=# select version();
                                                        version                                                        
-----------------------------------------------------------------------------------------------------------------------
 PostgreSQL 16.1 (IvorySQL 3.0) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4), 64-bit
(1 row)

**Comment by bigplaice** [comment]
This issue has been address in 3.2, so close it.
