### ISSUE TITLE
On branch REL_3_STABLE, running 'make world' results in an error

### ISSUE THREAD

**Issue by jrubyn0** [IvorySQL/IvorySQL#645]
The reproduction steps are as follows:
1.git checkout IVORY_REL_3_STABLE
2.git pull
3.make world
![image](https://github.com/IvorySQL/IvorySQL/assets/69285082/b3219c67-a627-4477-9f5c-444bdf6cde73)

**Comment by bigplaice** [comment]
fix the failure of doc build https://github.com/IvorySQL/IvorySQL/pull/646

**Comment by bigplaice** [comment]
The failure is about doc build and has been fixed by PR 646.
https://github.com/IvorySQL/IvorySQL/pull/646
