### ISSUE TITLE
Build warnings

### ISSUE THREAD

**Issue by 707330139** [IvorySQL/IvorySQL#649]
## Bug Report 
There is build warnings.

### IvorySQL Version
3.1

### OS Version (uname -a)
Linux localhost.localdomain 4.18.0-348.el8.x86_64 #1 SMP Tue Oct 19 15:14:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior
Althouth the build of code can be successful, there are many warnings in the output. 
Such as: 
	tablecmds.c:18328:10: warning: declaration of ‘constraintOid’ shadows a previous local
	execExprInterp.c:3992:13: warning: unused variable ‘argnull’

### Expected behavior/code
No build warning.

### Step to reproduce
make 

### Additional context that can be helpful for identifying the problem
N/A

**Comment by bigplaice** [comment]
https://github.com/IvorySQL/IvorySQL/pull/647

**Comment by bigplaice** [comment]
This issue had been addressed by following PR, so close it.
https://github.com/IvorySQL/IvorySQL/pull/647
