### ISSUE TITLE
Does not support data type VARCHAR2

### ISSUE THREAD

**Issue by sanuinfopro** [IvorySQL/IvorySQL#652]
## IvorySQL Version: 

2.3 and 3.1

### OS Version (uname -a):
Linux ivorysqltest.... 4.18.0-513.5.1.el8_9.x86_64 #1 SMP Fri Sep 29 05:21:10 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
Can create table but unable to define data type varchar2 and number. Need to replace with varchar and numeric
![image](https://github.com/IvorySQL/IvorySQL/assets/165761408/4a5ff831-0295-4a5f-822a-f37e08c0c87f)
![image](https://github.com/IvorySQL/IvorySQL/assets/165761408/f30d0d6e-4ea3-4346-b91c-50da87fb0e55)

### Expected behavior/code
- Able to support data type varchar2 and number

### Step to reproduce
SET compatible_mode TO oracle;
CREATE TABLE books (
    id     INT, 
    title  VARCHAR2(100), 
    author VARCHAR2(100),
    price  NUMBER);

### Additional context that can be helpful for identifying the problem
NA

**Comment by sanuinfopro** [comment]
unable to create table that contains column with data type varchar2, in the document it says version 2.3 and 3.1 supports data type varchar2 
![image](https://github.com/IvorySQL/IvorySQL/assets/165761408/d0bb703d-659e-43d6-9d0b-850712a076e1)

**Comment by balinorLiang** [comment]
@sanuinfopro Hello, thanks for your feedback. However, I have tried in my side, it works well, FYI.
**IvorySQL Version**: 3.1
**Step to reproduce**
ivorysql=# set ivorysql.compatible_mode TO oracle;
SET
ivorysql=# CREATE TABLE books (
ivorysql(# id INT,
ivorysql(# title VARCHAR2(100),
ivorysql(# author VARCHAR2(100),
ivorysql(# price NUMBER);
CREATE TABLE
ivorysql=# select version();
                                                        version

---------------------------------------------------------------------------------------------------------------
---------
 PostgreSQL 16.1 (IvorySQL 3.1) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20)
, 64-bit
(1 row)

**Comment by gaoxueyu** [comment]
> unable to create table that contains column with data type varchar2, in the document it says version 2.3 and 3.1 supports data type varchar2 ![image](https://private-user-images.githubusercontent.com/165761408/318670643-d0bb703d-659e-43d6-9d0b-850712a076e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDgyNTksIm5iZiI6MTcxMzQwNzk1OSwicGF0aCI6Ii8xNjU3NjE0MDgvMzE4NjcwNjQzLWQwYmI3MDNkLTY1OWUtNDNkNi05ZDBiLTg1MDcxMmEwNzZlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwMjM5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTFhZmQyMzgwYmNiMzUwNzQ4ZTdjMDRhMDcxY2JlNGVkM2JiMjk1Mjg2NzM0NWNkMzQ4YWNjOTQxZGQ4MTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HGs4Az46hj6uLJ1a9T7ANwjw3tJA3munA6OP7oheNjY)

Hi sanuinfopro, thank you for reporting the bug. 
BalinorLiang has validated it and confirmed that the functionality is working as expected. We could not reproduce the issue. 
We recommend using version 3.0 or higher. Now the latest version is 3.2.
Did he answer your question?

**Comment by sanuinfopro** [comment]
@balinorLiang  and @gaoxueyu, yes I managed to create table with data type varchar2 inside Ivorysql 3.2

**Comment by sanuinfopro** [comment]
@balinorLiang   and @gaoxueyu , yes I managed to create table with data type varchar2 inside Ivorysql 3.2
