### ISSUE TITLE
Request for package support in Ivorysql version 4

### ISSUE THREAD

**Issue by sanuinfopro** [IvorySQL/IvorySQL#653]
## Feature Request

The package compatible feature got removed in version 3.0 onwards but version 2.3 had it. I would like to request to build the new version of Ivorysql with package compatible feature.

**Comment by grantzhou** [comment]
we are indeed working on the package feature you mentioned. We anticipate including it in IvorySQL Version 4.0, which we aim to release concurrently with PostgreSQL 17 by the end of 2024.
