### ISSUE TITLE
In Oracle-compatible mode, querying date types will lack the hour, minute, and second parts

### ISSUE THREAD

**Issue by jrubyn0** [IvorySQL/IvorySQL#657]
### IvorySQL Version
3.2

### OS Version (uname -a)
CentOS 7

### Configuration options  ( config.status --config )
None

### Current Behavior
SET ivorysql.compatible to oracle;
CREATE TABLE test_date(a int, b date);
SET ivorysql.datetime_ignore_nls_mask =1;
INSERT INTO test_date values(1, '2023-10-27 10:54:55');
SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
SELECT * from test_date;
 a |          b
---+---------------------
 1 | 2023-10-27 00:00:00
(1 row)

The result is wrong;

### Expected behavior/code
ivorysql=# SELECT * from test_date;
 a |          b
---+---------------------
 1 | 2023-10-27 10:54:55
(1 row)

### Step to reproduce
SET ivorysql.compatible to oracle;
CREATE TABLE test_date(a int, b date);
SET ivorysql.datetime_ignore_nls_mask =1;
INSERT INTO test_date values(1, '2023-10-27 10:54:55');
SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
SELECT * from test_date;

**Comment by balinorLiang** [comment]
Thanks for your kindly reply. What's more, the step to reproduce is very clear and intuitive.

**Comment by gaoxueyu** [comment]
PR has been merged. 
You could find the feature via IVORY_REL_3_STABLE branch.
