### ISSUE TITLE
When selecting Oracle-compatible mode, attempting to insert data with a timestamp(7) type results in an error.

### ISSUE THREAD

**Issue by shaolinchu** [IvorySQL/IvorySQL#658]
### IvorySQL Version
3.2

### OS Version (uname -a)
CentOS 7

### Configuration options  ( config.status --config )
None

### Current Behavior
In Oracle-Compatible mode, IvorySQL appears to support timestamp(7) with precision exceeding 6. However, attempting to insert data will result in an error.

### Expected behavior/code
Allow to insert timestamp(7) type data

### Step to reproduce
ivorysql=#  SET ivorysql.compatible_mode to oracle;
ivorysql=#  CREATE TABLE timestamp_precision_7(id int, name text, created_at timestamp(7));
WARNING:  TIMESTAMP(7) effective number of fractional seconds is 6,the part of excess is 0
LINE 1: ...mestamp_precision_7(id int, name text, created_at timestamp(...
                                                             
WARNING:  TIMESTAMP(7) effective number of fractional seconds is 6,the part of excess is 0
CREATE TABLE
ivorysql=# INSERT INTO timestamp_precision_7 values(1, 'precision test', '2024-04-23 07:54:55.1234567');
ERROR:  timestamp(7) precision must be between 0 and 6
LINE 1: ...timestamp_precision_7 values(1, 'precision test', '2023-10-2...

**Comment by balinorLiang** [comment]
> ## Bug Report
> ### IvorySQL Version
> 3.2
> 
> ### OS Version (uname -a)
> CentOS 7
> 
> ### Configuration options ( config.status --config )
> None
> 
> ### Current Behavior
> In Oracle-Compatible mode, IvorySQL appears to support timestamp(7) with precision exceeding 6. However, attempting to insert data will result in an error.
> 
> ### Expected behavior/code
> Allow to insert timestamp(7) type data
> 
> ### Step to reproduce
> ivorysql=# SET ivorysql.compatible_mode to oracle; ivorysql=# CREATE TABLE timestamp_precision_7(id int, name text, created_at timestamp(7)); WARNING: TIMESTAMP(7) effective number of fractional seconds is 6,the part of excess is 0 LINE 1: ...mestamp_precision_7(id int, name text, created_at timestamp(...
> 
> WARNING: TIMESTAMP(7) effective number of fractional seconds is 6,the part of excess is 0 CREATE TABLE ivorysql=# INSERT INTO timestamp_precision_7 values(1, 'precision test', '2024-04-23 07:54:55.1234567'); ERROR: timestamp(7) precision must be between 0 and 6 LINE 1: ...timestamp_precision_7 values(1, 'precision test', '2023-10-2...
> 
> ### Additional context that can be helpful for identifying the problem

When IvorySQL 3.3 is released, this issue will be fixed. If you wanna try it now correctly, please re-install IvorySQL with source code based on IVORY_REL_3_STABLE branch.
