### ISSUE TITLE
Default SYSTIMESTAMP not working Oracle Mode

### ISSUE THREAD

**Issue by imranzaheer612** [IvorySQL/IvorySQL#661]
## Bug Report
Cannot use `SYSTIMESTAMP` function as default entry, in oracle mode
### IvorySQL Version
3.2
### Current Behavior
```
ERROR:  cannot use column reference in DEFAULT expression
LINE 3: mytime DATE DEFAULT SYSTIMESTAMP
```
### Expected behavior/code
It should recognize the `systimestamp` keyword

### Step to reproduce
```
postgres=# set ivorysql.compatible_mode=oracle;
SET
postgres=# CREATE TABLE testsystime
(
mytime DATE DEFAULT SYSTIMESTAMP
NOT NULL
);
ERROR:  cannot use column reference in DEFAULT expression
LINE 3: mytime DATE DEFAULT SYSTIMESTAMP

```

### Additional context that can be helpful for identifying the problem
I guess this bug is similar to this issue https://github.com/IvorySQL/IvorySQL/issues/633

**Comment by gaoxueyu** [comment]
Issue has been fixed by #663  and will be included in Release 3.3.
