### ISSUE TITLE
support redhat 9

### ISSUE THREAD

**Issue by shawn0915** [IvorySQL/IvorySQL#669]
## Enhancement

```
Status code: 404 for https://yum.highgo.ca/dists/ivorysql-rpms/3/redhat/rhel-9-x86_64/repodata/repomd.xml
```

when I install ivorysql under redhat 9, it can not found the package via yum/dnf, 

shall we support for it?

**Comment by balinorLiang** [comment]
@shawn0915 Yep, IvorySQL needs to support Redhat 9 sooner or later, team members will discuss this work recently.

**Comment by balinorLiang** [comment]
@shawn0915 Both RPM and yum installations of IvorySQL3.3 are already supported in RHEL9. Please try the new RPM packages in the 3.3 Release, or use the following command to install via yum:
`yum install -y ivorysql3 ivorysql3-server ivorysql3-contrib ivorysql3-test`
