### ISSUE TITLE
default value about ivorysql.comatible_mode

### ISSUE THREAD

**Issue by jerome-peng** [IvorySQL/IvorySQL#698]
### IvorySQL Version
IvorySQL 3.2

### Current Behavior
In the docment  7.1.1. compatible_mode (enum)
[[IvorySQL Document Site](https://docs.ivorysql.org/)](https://docs.ivorysql.org/en/ivorysql-doc/v3.1/v3.1/8#configuration-parameters)

it said: The default value is postgres.  However, in the database, I use show command, the value is pg

```
postgres=# show ivorysql.compatible_mode;
ivorysql.compatible_mode
----------------------------
pg
(1 row)
```

### Expected behavior/code
the default value of ivorysql.comatible_mode in doc must be same to the db

**Comment by SAMBILI** [comment]
try this
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by shawn0915** [comment]
彭老师说的对，文档应该修正一下。

**Comment by gaoxueyu** [comment]
Hi jerome-peng and Shawn, thanks very much for your comments.
Document has been updated for all 3.X release. (https://docs.ivorysql.org/en/ivorysql-doc/v3.4/v3.4/8#configuration-parameters)
Free feel to let me know if there is any missing.

**Comment by balinorLiang** [comment]
https://github.com/IvorySQL/ivorysql_web/pull/86 fixed this issue

**Comment by flyingbeecd** [comment]
![Image](https://github.com/user-attachments/assets/17207017-4f09-4135-91dd-3721072f82a1)  默认安装后是pg，和文档描述好像不一样呢
