### ISSUE TITLE
type varchar2 does not exist

### ISSUE THREAD

**Issue by jerome-peng** [IvorySQL/IvorySQL#75]
### Configuration options 
$ /opt/ipg/bin/pg_config |grep CONFIGURE
CONFIGURE =  '--prefix=/opt/ipg' '--with-openssl' '--with-includes=/usr/include/openssl'

### Current Behavior
postgres=# CREATE TABLE test(x INT, y VARCHAR2(100));
ERROR:  type "varchar2" does not exist
LINE 1: CREATE TABLE test(x INT, y VARCHAR2(100));

### Expected behavior/code
create table success

### Step to reproduce
CREATE TABLE test(x INT, y VARCHAR2(100));

**Comment by BingAo-Office** [comment]
did you set parameter compatible_mode to oracle?

**Comment by jerome-peng** [comment]
> did you set parameter compatible_mode to oracle?

现在解决了：1 需要设置compatible_mode=oracle   2 用户的search_path需要包含oracle schema。

thanks!
