### ISSUE TITLE
Ivorysql is terminated

### ISSUE THREAD

**Issue by killerwzb** [IvorySQL/IvorySQL#80]
Bug Report

IvorySQL Version: 1.2

test=# select version();
                                          version
--------------------------------------------------------------------------------------------
 PostgreSQL 14.2 (IvorySQL 1.2) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.0, 64-bit
(1 row)

OS Version : centos 7

Linux monitor 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

SQL:

### 1 create table and insert into some rows

create table hier
(parents char(20),
child char(20)
);
insert into hier values('Earth','Asia');
insert into hier values('Earth','Australia');
insert into hier values('Earth','Europe');
insert into hier values('Earth','North America');
insert into hier values('Asia','China');
insert into hier values('Asia','Japan');
insert into hier values('Australia','New South Wales');
insert into hier values('New South Wales','Sydney');
insert into hier values('California','Redwood Shores');
insert into hier values('Canada','Ontario');
insert into hier values('China','Beijing');
insert into hier values('England','London');
insert into hier values('Europe','United Kingdom');
insert into hier values('Japan','Osaka');
insert into hier values('Japan','Tokyo');
insert into hier values('North America','Canada');
insert into hier values('North America','USA');
insert into hier values('Ontario','Ottawa');
insert into hier values('Ontario','Toronto');
insert into hier values('USA','California');
insert into hier values('United Kingdom','England');

###2  Run this sql

select level,lpad(' ',level*3)||child child  from hier start with parents ='Earth' connect by prior child = parents;

###3 Get error:
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.

**Comment by KingZhaoTPG** [comment]
Hi @killerwzb, thanks a lot for your test. I also ran your TC in V.12 and it seems to be an issue with the LEVEL pseudo-column. if you want to test the lpad function, I suggest you modify you TC as follows:

```
-- SQL statement
select level,lpad('IvorySQL',10)|| 'child' 
  from hier 
  start with parents ='Earth' 
  connect by prior child = parents;

hges_test=# select level,lpad('IvorySQL',10)|| 'child'
hges_test-#   from hier
hges_test-#   start with parents ='Earth'
hges_test-#   connect by prior child = parents;
 LEVEL |      lpad
-------+-----------------
     1 |   IvorySQLchild
     1 |   IvorySQLchild
     1 |   IvorySQLchild
     1 |   IvorySQLchild
     2 |   IvorySQLchild
     2 |   IvorySQLchild
     2 |   IvorySQLchild
     2 |   IvorySQLchild
     2 |   IvorySQLchild
     2 |   IvorySQLchild
     3 |   IvorySQLchild
     3 |   IvorySQLchild
     3 |   IvorySQLchild
     3 |   IvorySQLchild
     3 |   IvorySQLchild
     3 |   IvorySQLchild
     3 |   IvorySQLchild
     4 |   IvorySQLchild
     4 |   IvorySQLchild
     4 |   IvorySQLchild
     4 |   IvorySQLchild
(21 rows)

```

You must enclose child with ' ', otherwise PG will report an error

```
hges_test=# select level,lpad('IvorySQL',10)|| child  from hier start with parents ='Earth' connect by prior child = parents;   ERROR:  column reference "child" is ambiguous
LINE 1: select level,lpad('IvorySQL',10)|| child  from hier start wi...
```

As I said, there is a issue with the level, and I run the following TC which also causes the server to terminate.


```
hges_test=#
hges_test=# select level from hier start with parents ='Earth' connect by prior child = parents;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!?>
```

Anyway, we'll work on fixing these issues.
