### ISSUE TITLE
Create package using VARCHAR2 type prompt does not exist

### ISSUE THREAD

**Issue by sun-hchao** [IvorySQL/IvorySQL#82]
The VARCHAR2 type cannot be used to create a package using the official documentation sample

For example:
oracle=# select version();
                                                        version
------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.2 (IvorySQL 1.2) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
(1 行记录)

oracle=# show compatible_mode ;
 compatible_mode
-----------------
 oracle
(1 行记录)

oracle=# CREATE TABLE test(x INT, y VARCHAR2(100));
CREATE TABLE
oracle=# INSERT INTO test VALUES (1, 'One');
INSERT 0 1
oracle=# INSERT INTO test VALUES (2, 'Two');
INSERT 0 1
oracle=# INSERT INTO test VALUES (3, 'Three');
INSERT 0 1
oracle=# CREATE OR REPLACE PACKAGE example AUTHID DEFINER AS
oracle$#    -- Declare public type, cursor, and exception:
oracle$#    TYPE rectype IS RECORD (a INT, b VARCHAR2(100));
oracle$#    CURSOR curtype RETURN rectype%rowtype;
oracle$#
oracle$#    rec rectype;
oracle$#
oracle$#    -- Declare public subprograms:
oracle$#    FUNCTION somefunc (
oracle$#          last_name VARCHAR2,
oracle$#          first_name VARCHAR2,
oracle$#          email VARCHAR2
oracle$#    ) RETURN NUMBER;
oracle$#
oracle$#    -- Overload preceding public subprogram:
oracle$#    PROCEDURE xfunc (emp_id NUMBER);
oracle$#    PROCEDURE xfunc (emp_email VARCHAR2);
oracle$# END example;
oracle$# /
错误:  类型 "varchar2" 不存在

**Comment by rasifr** [comment]
This issue has been fixed and verified. So closing it.
