### ISSUE TITLE
The description of the parameter (weekday) of the function (next_day) in the document is incorrect

### ISSUE THREAD

**Issue by liuxintang** [IvorySQL/IvorySQL#92]
##Current Status
In the document, the parameter (weekday) of the function (next_day) is noted as follows.
0 means Sunday.
![image](https://user-images.githubusercontent.com/99459384/157825954-0c83b6c3-bedd-457b-a764-3ea5608c8b95.png)
However, when the parameter (weekday) is set to 0, there is an error in execution.
![image](https://user-images.githubusercontent.com/99459384/157825977-4d5d9f1e-4e88-4038-8d5c-282135876553.png)
After verification, the integer value of the parameter (weekday) is 1 to 7, not 0 to 6, 1 represents Sunday, the document is incorrect. the value of Oracle is also 1 to 7.
![image](https://user-images.githubusercontent.com/99459384/157825998-1f24c577-0fe9-4ef5-b9e4-79c1e81b3a16.png)
## Enhancement
Please confirm and revise the description in the document.

**Comment by KingZhaoTPG** [comment]
Hi @liuxintang , This is a bug, we will fix it. thanks for your continued output. We have built a huge WeChat communication group for IvorySQL, there are many experts and PG enthusiasts in it, if you are interested, welcome to join our group, maybe your questions can be answered asap. If you want to join us, please email me(zhaoshengbin@highgo.com).

**Comment by BingAo-Office** [comment]
please， report the bug at https://github.com/IvorySQL/Ivory-www

**Comment by liuxintang** [comment]
@BingAo-Office
Submitted at https://github.com/IvorySQL/Ivory-www. number is 36.
Please confirm.

**Comment by grantzhou** [comment]
This issue is a document issue and it was moved to [Ivory-www](https://github.com/IvorySQL/Ivory-www) project to
https://github.com/IvorySQL/Ivory-www/issues/36
