### ISSUE TITLE
The description of the parameter (fmt) of the function (numtodsinterval) in the document is incorrect

### ISSUE THREAD

**Issue by liuxintang** [IvorySQL/IvorySQL#93]
##Current Status
In the document, the parameter (fmt) of the function (numtodsinterval) is noted as follows.
The parameter (fmt) does not contain year and month.
![image](https://user-images.githubusercontent.com/99459384/157827932-ebb2b494-9648-4793-9055-e3294cc5407f.png)

However, when the parameter (fmt) are year and month, no error is reported and the result is correct.
![image](https://user-images.githubusercontent.com/99459384/157827952-48383540-2ea6-4f49-b6d8-c49e10ecdd45.png)
## Enhancement
Please confirm whether it is an error of document or an error of the function's logic.

**Comment by BingAo-Office** [comment]
please， report  the  bug  at https://github.com/IvorySQL/Ivory-www

**Comment by liuxintang** [comment]
@BingAo-Office , I think this problem is a bug in the function logic, not a bug in the documentation.
Because the parameters of the function (numtoyminterval) are year and month.

**Comment by gaoxueyu** [comment]
Thanks for your reporting. Issue has been fixed at IvorySQL 3.1.
