### ISSUE TITLE
The function (numtoyminterval) is inconsistent with oracle for decimal calculations

### ISSUE THREAD

**Issue by liuxintang** [IvorySQL/IvorySQL#94]
## Bug Report
The function (numtoyminterval) is inconsistent with oracle for decimal calculations
### IvorySQL Version
1.1
### OS Version (uname -a)
Linux
### Configuration options  ( config.status --config )
compatible_mode =oracle
### Current Behavior
Test SQL：
select timestamp'2022-02-18 10:55:20' + numtoyminterval(100.6,'year') from dual;
select timestamp'2022-02-18 10:55:20' + numtoyminterval(100.6,'month') from dual;
Test result：
IvorySQL V1.1：
![image](https://user-images.githubusercontent.com/99459384/157829749-444649e3-7fad-4595-a920-3ec858eecda3.png)
Oracle：
![image](https://user-images.githubusercontent.com/99459384/157829778-b41e6c89-4e80-41ee-9680-8f26331a98c6.png)
### Expected behavior
Consistent with Oracle's results

**Comment by gaoxueyu** [comment]
Thanks for your reporting. Issue has been fixe at IvorySQL 3.1.
